
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\codyh\Downloads\build\assets\frame3")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1192x800")
window.configure(bg = "#AFAFAF")


canvas = Canvas(
    window,
    bg = "#AFAFAF",
    height = 800,
    width = 1192,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    460.0,
    63.0,
    anchor="nw",
    text="Settings page",
    fill="#000000",
    font=("Inter Bold", 40 * -1)
)

canvas.create_text(
    50.0,
    173.0,
    anchor="nw",
    text="Degrees: ",
    fill="#000000",
    font=("Inter Bold", 36 * -1)
)

canvas.create_text(
    222.0,
    177.0,
    anchor="nw",
    text="C",
    fill="#000000",
    font=("Inter Bold", 36 * -1)
)

canvas.create_rectangle(
    250.0,
    173.0,
    313.0,
    224.0,
    fill="#FFFFFF",
    outline="")
window.resizable(False, False)
window.mainloop()
